apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask-app
spec:
  containers:
    - name: flask-container
      image: engineerwithspecs02/my-flask:v1
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: flask-volume
          mountPath: /volume/data


  volumes:
    - name: flask-volume
      persistentVolumeClaim:
        claimName: flask-claim
